services:
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '6432:5432'
    volumes:
      - db_volume:/var/lib/postgresql/data

  api:
    build:
      context: ./
    image: tracker
    env_file: [ ./.env ]
    ports: [ "9881:9881" ]
    environment:
      - PORT=9883
    volumes:
      - ./:/opt
    depends_on: [ db ]

  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 6379:6379

volumes:
  db_volume: